version: '3'
services:
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - '3000:80'

  api:
    restart: always  
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '5000:5000'

  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    #ports:
      #- '3000:8080'